-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 12:24:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_items
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_items` ;

-- -----------------------------------------------------
-- Schema bd_items
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_items` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `bd_items` ;

-- -----------------------------------------------------
-- Table `bd_items`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_items`.`item` ;

CREATE TABLE IF NOT EXISTS `bd_items`.`item` (
  `id` INT NOT NULL,
  `campo1` DOUBLE NULL,
  `campo2` DOUBLE NULL,
  `campo3` DOUBLE NULL,
  `campo4` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
